name: C++ Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up C++ compiler
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build C++ program
      run: g++ hello_world.cpp -o hello_world

    - name: Run C++ program
      run: ./hello_world
